
joystickClient: client.c ../JoystickServer/joystickconvert.c ../JoystickInput/JoystickInput.c ../rs232Server/rs232Server.c ;gcc -o joystickClient client.c ../JoystickServer/joystickconvert.c ../JoystickInput/JoystickInput.c ../rs232Server/rs232Server.c
